apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obmondo-k8s-agent
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obmondo
  project: default
  sources:
    - repoURL: {{.KubeAidRepo}}
      path: argocd-helm-charts/obmondo-k8s-agent
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/{{.ClusterName}}/argocd-apps/values-obmondo-k8s-agent.yaml
    - repoURL: {{.KubeAidConfigRepo}}
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
