apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  sources:
    - repoURL: {{.KubeAidRepo}}
      path: argocd-helm-charts/traefik
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/{{.ClusterName}}/argocd-apps/values-traefik.yaml
    - repoURL: {{.KubeAidConfigRepo}}
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
